name: Check links on schedule
on:
  schedule:
    - cron: "59 23 * * 0" # Runs every Sunday at 23:59
  push: # for testing purposes, do not merge
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: filiph/linkcheck@3.0.0
      with:
        arguments: https://www.scaleway.com/en/docs/ >> linkcheck_output.txt
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: linkcheck_output.txt
        path: linkcheck_output.txt
