name: Check links on schedule
on:
  schedule:
    - cron: "59 23 * * 0" # Runs every Sunday at 23:59
  push: # for testing purposes, do not merge
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: filiph/linkcheck@3.0.0
      id: check_links
      with:
        arguments: https://www.scaleway.com/en/docs/ >> $GITHUB_OUTPUT
    - name: Print output
      run: |
        echo "${{steps.check_links.outputs.*}}"
