name: Check links on schedule
on:
  schedule:
    - cron: "59 23 * * 0" # Runs every Sunday at 23:59
  push: # for testing purposes, do not merge
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: filiph/linkcheck@3.0.0
        with:
          arguments: https://www.scaleway.com/en/docs/serverless/ >> linkcheck_output.txt
      - name: Upload a Build Artifact
        if: always() # Triggers step if previous step fails. Must be added to consecutive steps as well.
        uses: actions/upload-artifact@v4.4.3
        with:
          name: linkcheck_output.txt
          path: linkcheck_output.txt
      - name: Send a saved artifact to a Slack workflow
        if: always() # Triggers step if previous step fails. Must be added to consecutive steps as well.
        uses: slackapi/slack-github-action@v2.0.0 # ref: https://github.com/slackapi/slack-github-action
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Link check results."
