name: Check links on schedule
on:
  schedule:
    - cron: "59 23 * * 0" # Runs every Sunday at 23:59
  push: # for testing purposes, do not merge
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: filiph/linkcheck@3.0.0
        with:
          arguments: https://www.scaleway.com/en/docs/serverless/ >> linkcheck_output.txt
      - name: Parse output to variable
        if: always()
        run: |
          {
            echo 'LINKCHECK_OUTPUT<<EOF'
            cat linkcheck_output.txt
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Send message to Slack
        if: always()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Link check results:\n $LINKCHECK_OUTPUT"
